#! /bin/sh
feh --bg-scale ~/.config/wallpapers/space_art_nebula_126460_1920x1080.jpg
picom --config ~/.config/picom/picom.conf &
~/.config/polybar/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Gpick state=floating
bspc rule -a feh state=floating rectangle=1376x625+0+0
#COLORS
bspc config focused_border_color "#241c21"
bspc config normal_border_color "#241c21"

